c cycle sub
g seek 0 absolute
G seek -2 absolute
h seek -5
l seek +5
j add volume -5
k add volume +5
J add sub-scale -0.1
K add sub-scale +0.1
UP add volume +5
DOWN add volume -5
N playlist-prev
M playlist-next
s ignore
