add_newline=false

[character]
success_symbol="[%](fg:#00d600)"
error_symbol="[%](fg:#00d600)"

[directory]
style="bold fg:#006ed0"

[username]
style_user="bold blue"

[python]
style="bold blue"
symbol=" "
python_binary="python3"

#-------------Disabled modules-------------

[package]
disabled=true

[aws]
disabled=true

[cmd_duration]
disabled=true

[conda]
disabled=true

[crystal]
disabled=true

[docker_context]
disabled=true

[dotnet]
disabled=true

[elixir]
disabled=true

[elm]
disabled=true

[erlang]
disabled=true

[golang]
disabled=true

[java]
disabled=true

[julia]
disabled=true

[line_break]
disabled=true

[hg_branch]
disabled=true

[nim]
disabled=true

[nix_shell]
disabled=true

[nodejs]
disabled=true

[ocaml]
disabled=true

[php]
disabled=true

[ruby]
disabled=true

[rust]
disabled=true

[singularity]
disabled=true

[terraform]
disabled=true

[zig]
disabled=true

[purescript]
disabled=true
